# -*- coding: utf-8 -*-
"""Whisper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-d6Ehp8o3oLuQMyRNTr665h4ihnMRkzl
"""

!pip install cohere

pip install -U openai-whisper

pip install git+https://github.com/openai/whisper.git

pip install --upgrade --no-deps --force-reinstall git+https://github.com/openai/whisper.git

pip install setuptools-rust

!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg

!whisper "Audio.m4a" --model large

from google.colab import files
import time

# Nom du fichier déjà présent dans Colab
filename = 'Audio.txt'

# Attendre 200 secondes avant le téléchargement
time.sleep(60)

# Lancer le téléchargement automatique
files.download(filename)